baseURL: "https://tahiti-dive-management.com/"
defaultContentLanguage: "en"
disableKinds: ["section", "taxonomy", "term", "RSS", "robotsTXT"]
enableRobotsTXT: true

title: Tahiti Dive Management

theme: bootstrap

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about"
      weight: 2
    - name: "Services"
      url: "/services"
      weight: 3
    - name: "Contact"
      url: "/contact"
      weight: 4

params:
  logo: "/images/logo.webp"
  heroTitle: "Tahiti Dive Management"
  heroImage: "/images/hero-bg.webp"

  disable_share: true
  ananke.socials:
    facebook:
        username: Tahiti-Dive-Management-219479998998180
    instagram:
        username: tahitidivemanagement
    youtube:
        username: UCoYn6WcmoT_xlU6xy58vSpQ

  title: "Tahiti Dive Management"

    # The "description" of your website. This is used in the meta data of your generated html.
  description: "Private diving with Tahiti Dive Management"
  copyright: 'Copyright © {year} Tahiti Dive Management. All Rights Reserved.'

  meta:
    keywords: "some, keywords, for, seo, you, know, google, duckduckgo, and, such"

  contacts:
    - label: "email"
      value: " tdm.dive@gmail.com"
      url: "mailto:tdm.dive@gmail.com"
      icon: "fa fa-envelope"
    - label: "phone"
      value: "(+689) 87 32 66 80"
      url: "tel:+68987326680"
      icon: "fa fa-phone"

languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 10
  fr:
    contentDir: content/fr
    languageName: "Français"
    weight: 20
